# this is a docker compose for running the app locally

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news-fetcher-container
    ports:
      - "4000:5000"
    environment:
      VITE_WEBPAGE_URL: http://localhost:4000
      FLASK_ENV: development
      FLASK_APP: src.app
      FLASK_DEBUG: 1
      PYTHONDONTWRITEBYTECODE: 1
    tty: true
    stdin_open: true
